import type { Metadata } from 'next';
import { Inter, Oswald } from 'next/font/google';

import './globals.css';

export const inter = Inter({ subsets: ['latin'], display: 'swap' });

export const oswald = Oswald({ subsets: ['latin'], display: 'swap' });

export const metadata: Metadata = {
  title: 'Portfolio',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} ${oswald.className}`}>
        {children}
      </body>
    </html>
  );
}
